set echo on
set pages 200
set lines 220

prompt ============================================================
prompt 04 - Three-table data modeling lab
prompt Purpose:
prompt   - DM_CUSTOMERS: parent entity
prompt   - DM_ACCOUNTS: parent entity
prompt   - DM_ACCOUNT_CUSTOMERS: bridge table for many-to-many
prompt Safe to rerun in lab: drops only DM_* objects below.
prompt ============================================================

begin
  execute immediate 'drop table dm_account_customers purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

begin
  execute immediate 'drop table dm_accounts purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

begin
  execute immediate 'drop table dm_customers purge';
exception
  when others then
    if sqlcode != -942 then raise; end if;
end;
/

create table dm_customers (
  id          number generated by default as identity,
  full_name   varchar2(100) not null,
  email       varchar2(200) not null,
  created_at  timestamp default systimestamp not null,
  constraint pk_dm_customers primary key (id),
  constraint uq_dm_customers_email unique (email)
);

create table dm_accounts (
  id          number generated by default as identity,
  acct_no     varchar2(30) not null,
  acct_type   varchar2(20) not null,
  status      varchar2(20) default 'ACTIVE' not null,
  created_at  timestamp default systimestamp not null,
  constraint pk_dm_accounts primary key (id),
  constraint uq_dm_accounts_acct_no unique (acct_no),
  constraint ck_dm_accounts_type check (acct_type in ('SAVINGS', 'CHECKING')),
  constraint ck_dm_accounts_status check (status in ('ACTIVE', 'CLOSED'))
);

create table dm_account_customers (
  account_id   number not null,
  customer_id  number not null,
  role_name    varchar2(30) default 'OWNER' not null,
  linked_at    timestamp default systimestamp not null,
  constraint pk_dm_account_customers primary key (account_id, customer_id),
  constraint fk_dm_acctcust_account foreign key (account_id)
    references dm_accounts(id),
  constraint fk_dm_acctcust_customer foreign key (customer_id)
    references dm_customers(id),
  constraint ck_dm_acctcust_role check (role_name in ('OWNER', 'CO_OWNER', 'AUTHORIZED_USER'))
);

create index ix_dm_acctcust_customer
  on dm_account_customers(customer_id);

insert into dm_customers (full_name, email)
select 'Customer ' || level, 'customer' || level || '@lab.local'
from dual
connect by level <= 5;

insert into dm_accounts (acct_no, acct_type)
select 'ACC-' || to_char(level, 'FM000'), case when mod(level, 2) = 0 then 'CHECKING' else 'SAVINGS' end
from dual
connect by level <= 4;

insert into dm_account_customers (account_id, customer_id, role_name)
values (1, 1, 'OWNER');

insert into dm_account_customers (account_id, customer_id, role_name)
values (1, 2, 'CO_OWNER');

insert into dm_account_customers (account_id, customer_id, role_name)
values (2, 2, 'OWNER');

insert into dm_account_customers (account_id, customer_id, role_name)
values (3, 3, 'OWNER');

insert into dm_account_customers (account_id, customer_id, role_name)
values (4, 1, 'AUTHORIZED_USER');

commit;

prompt ============================================================
prompt Data check
prompt ============================================================

select 'DM_CUSTOMERS' as table_name, count(*) as row_count from dm_customers
union all
select 'DM_ACCOUNTS', count(*) from dm_accounts
union all
select 'DM_ACCOUNT_CUSTOMERS', count(*) from dm_account_customers
order by table_name;

select a.acct_no,
       c.full_name,
       ac.role_name
from dm_account_customers ac
join dm_accounts a
  on a.id = ac.account_id
join dm_customers c
  on c.id = ac.customer_id
order by a.acct_no, c.full_name;

prompt ============================================================
prompt Cardinality evidence from data
prompt ============================================================

select account_id, count(*) as customer_count
from dm_account_customers
group by account_id
having count(*) > 1
order by account_id;

select customer_id, count(*) as account_count
from dm_account_customers
group by customer_id
having count(*) > 1
order by customer_id;

prompt ============================================================
prompt Metadata relationship discovery
prompt ============================================================

select c.table_name as child_table,
       cc.column_name as child_column,
       p.table_name as parent_table,
       pc.column_name as parent_column
from user_constraints c
join user_cons_columns cc
  on cc.constraint_name = c.constraint_name
 and cc.table_name = c.table_name
join user_constraints p
  on p.constraint_name = c.r_constraint_name
join user_cons_columns pc
  on pc.constraint_name = p.constraint_name
 and pc.position = cc.position
where c.constraint_type = 'R'
  and c.table_name like 'DM\_%' escape '\'
order by c.table_name, cc.position;

with fk_cols as (
  select c.table_name,
         c.constraint_name,
         cc.column_name,
         cc.position
  from user_constraints c
  join user_cons_columns cc
    on cc.constraint_name = c.constraint_name
   and cc.table_name = c.table_name
  where c.constraint_type = 'R'
    and c.table_name like 'DM\_%' escape '\'
),
fk_summary as (
  select table_name,
         count(distinct constraint_name) as fk_count,
         count(*) as fk_col_count,
         listagg(column_name, ', ') within group (order by column_name) as fk_columns_sorted
  from fk_cols
  group by table_name
),
key_cols as (
  select c.table_name,
         c.constraint_type,
         c.constraint_name,
         cc.column_name
  from user_constraints c
  join user_cons_columns cc
    on cc.constraint_name = c.constraint_name
   and cc.table_name = c.table_name
  where c.constraint_type in ('P', 'U')
    and c.table_name like 'DM\_%' escape '\'
),
key_summary as (
  select table_name,
         constraint_type,
         constraint_name,
         listagg(column_name, ', ') within group (order by column_name) as key_columns_sorted
  from key_cols
  group by table_name, constraint_type, constraint_name
),
col_summary as (
  select table_name,
         count(*) as total_columns
  from user_tab_columns
  where table_name like 'DM\_%' escape '\'
  group by table_name
)
select f.table_name,
       f.fk_count,
       f.fk_columns_sorted,
       k.constraint_type as matching_key_type,
       k.key_columns_sorted,
       col.total_columns,
       (col.total_columns - f.fk_col_count) as non_fk_columns,
       case
         when k.key_columns_sorted = f.fk_columns_sorted
              and (col.total_columns - f.fk_col_count) <= 3
         then 'LIKELY_MANY_TO_MANY_BRIDGE'
         when f.fk_count >= 2
         then 'POSSIBLE_BRIDGE_OR_BUSINESS_ENTITY'
       end as classification
from fk_summary f
join col_summary col
  on col.table_name = f.table_name
left join key_summary k
  on k.table_name = f.table_name
 and k.key_columns_sorted = f.fk_columns_sorted
where f.fk_count >= 2
order by classification, f.table_name;
